apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaydeployment
  labels:
    app: my-app
  namespace: 3gays
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: gay-image
          image: ghcr.io/stefanprodan/podinfo
          
---
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
  namespace: 3gays
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80      # External Port
      targetPort: 8080 # Pod Port
