# app 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaydeployment
  labels:
    app: my-app
    version: blue
  namespace: 3gays
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
      version: blue
  template:
    metadata:
      labels:
        app: my-app
        version: blue 
    spec:
      containers:
        - name: gay-image
          image: ghcr.io/stefanprodan/podinfo
          env: 
            - name: PODINFO_UI_MESSAGE
              value: "Niete"

---
# app 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaydeployment2
  labels:
    app: my-app
    version: red
  namespace: 3gays
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
      version: red
  template:
    metadata:
      labels:
        app: my-app
        version: red
    spec:
      containers:
        - name: gay-image
          image: ghcr.io/stefanprodan/podinfo
          env: 
            - name: PODINFO_UI_MESSAGE
              value: "Jackpot Wuuh"
---
# clusterip 1
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
  namespace: 3gays
spec:
  type: ClusterIP
  selector:
    app: my-app
    version: blue
  clusterIP: 10.109.0.2
  ports:
    - name: podinfo
      protocol: TCP
      port: 80
      targetPort: 9898
---
# clusterip 2
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-canary-service
  namespace: 3gays
spec:
  type: ClusterIP
  selector:
    app: my-app
    version: red
  clusterIP: 10.109.0.3
  ports:
    - name: podinfo
      protocol: TCP
      port: 80
      targetPort: 9898
---
#ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-canary-ingress
  namespace: 3gays
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "99"
spec:
  ingressClassName: nginx
  rules:
    - host: 3gays.k8s.schoeppi5.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-clusterip-service
                port:
                  number: 80
---
#ingress 2
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: 3gays
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: 3gays.k8s.schoeppi5.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-clusterip-canary-service
                port:
                  number: 80
