# app 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaydeployment
  labels:
    app: my-app
  namespace: 3gays
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: gay-image
          image: ghcr.io/stefanprodan/podinfo
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: gay-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gay-pvc
  namespace: 3gays
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

---
# clusterip 
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
  namespace: 3gays
spec:
  type: ClusterIP
  selector:
    app: my-app
  clusterIP: 10.109.0.2
  ports:
    - name: podinfo
      protocol: TCP
      port: 80
      targetPort: 9898
---
#ingress 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: 3gays
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: 3gays.k8s.schoeppi5.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-clusterip-service
                port:
                  number: 80
